# Copyright: Ankitects Pty Ltd and contributors
# License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

"""Seed a fresh collection with the bundled default Exam P content (NO AI).

This makes a first-time BrainLift user land on a collection that already has the
official SOA Exam P sample questions, mapped to the ``ExamP::*`` topic tags the
coverage/dashboard logic reads. It is:

* **Deterministic** -- the content is the pre-built :mod:`anki.brainlift.examp_seed`
  data module (derived from the freely-published SOA sample questions/solutions);
  nothing is generated by a language model.
* **Additive & safe** -- it never touches an existing user's data. It seeds only
  when the collection has no cards at all, and it records a config flag so it
  runs at most once. All work is wrapped so a failure can never crash startup.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from anki.collection import Collection

# Config flag recording that we've already seeded (syncs across devices).
CONFIG_KEY = "brainlift_seeded_default"

DECK_NAME = "Exam P — Sample Questions"
BASIC_NOTETYPE = "Basic"


def _has_any_cards(col: Collection) -> bool:
    """True if the collection already has content the user owns."""
    return bool(col.db.scalar("select count() from cards"))


def _basic_notetype(col):
    """Return the Basic notetype, adding the stock one if it's missing."""
    notetype = col.models.by_name(BASIC_NOTETYPE)
    if notetype is not None:
        return notetype
    from anki import stdmodels

    stdmodels._legacy_add_basic_model(col)
    return col.models.by_name(BASIC_NOTETYPE)


def maybe_seed_default_deck(col: Collection) -> int:
    """Seed the default Exam P deck if appropriate. Returns notes added.

    Returns 0 (does nothing) when the seed flag is already set, when the
    collection already contains cards, or if anything goes wrong. Idempotent.
    """
    try:
        if col.get_config(CONFIG_KEY, False):
            return 0
        if _has_any_cards(col):
            # User already has their own content -- don't touch it, but record
            # that we won't auto-seed later either.
            col.set_config(CONFIG_KEY, True)
            return 0

        from anki.brainlift.examp_seed import SEED_CARDS

        if not SEED_CARDS:
            return 0

        notetype = _basic_notetype(col)
        if notetype is None:
            return 0
        field_names = [f["name"] for f in notetype["flds"]]
        front_field = "Front" if "Front" in field_names else field_names[0]
        back_field = "Back" if "Back" in field_names else field_names[1]

        deck_id = col.decks.id(DECK_NAME)

        added = 0
        for card in SEED_CARDS:
            note = col.new_note(notetype)
            note[front_field] = card.get("front", "")
            note[back_field] = card.get("back", "")
            tags = card.get("tags") or []
            if tags:
                note.tags = list(tags)
            col.add_note(note, deck_id)
            added += 1

        col.set_config(CONFIG_KEY, True)
        return added
    except Exception:
        # Seeding is best-effort and must never crash the app / startup.
        return 0
