# Copyright: Ankitects Pty Ltd and contributors
# License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

"""Seed a fresh collection with the bundled default Exam P content (NO AI).

This makes a first-time BrainLift user land on a collection that already has the
official SOA Exam P sample questions, mapped to the ``ExamP::*`` topic tags the
coverage/dashboard logic reads. It is:

* **Deterministic** -- the content is the pre-built :mod:`anki.brainlift.examp_seed`
  data module (derived from the freely-published SOA sample questions/solutions);
  nothing is generated by a language model.
* **Additive & safe** -- it never touches an existing user's data. It seeds only
  when the collection has no cards at all, and it records a config flag so it
  runs at most once. All work is wrapped so a failure can never crash startup.
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from anki.collection import Collection

# Config flag recording that we've already seeded (syncs across devices).
CONFIG_KEY = "brainlift_seeded_default"
# Config flag recording that we've repaired stale/garbled seed content once.
REPAIR_FLAG = "brainlift_seed_repaired_v1"

DECK_NAME = "Exam P — Sample Questions"
BASIC_NOTETYPE = "Basic"

# Parses the SOA source question number out of a card's attribution line, e.g.
# "...Sample Questions/Solutions, Q3. https://..." -> 3. Present on both the
# clean bundled cards and the older garbled ones, so it's a stable join key.
_QNUM_RE = re.compile(r"Sample Questions/Solutions,\s*Q(\d+)\b")


def _has_any_cards(col: Collection) -> bool:
    """True if the collection already has content the user owns."""
    return bool(col.db.scalar("select count() from cards"))


def _basic_notetype(col):
    """Return the Basic notetype, adding the stock one if it's missing."""
    notetype = col.models.by_name(BASIC_NOTETYPE)
    if notetype is not None:
        return notetype
    from anki import stdmodels

    stdmodels._legacy_add_basic_model(col)
    return col.models.by_name(BASIC_NOTETYPE)


def maybe_seed_default_deck(col: Collection) -> int:
    """Seed the default Exam P deck if appropriate. Returns notes added.

    Returns 0 (does nothing) when the seed flag is already set, when the
    collection already contains cards, or if anything goes wrong. Idempotent.
    """
    try:
        if col.get_config(CONFIG_KEY, False):
            return 0
        if _has_any_cards(col):
            # User already has their own content -- don't touch it, but record
            # that we won't auto-seed later either.
            col.set_config(CONFIG_KEY, True)
            return 0

        from anki.brainlift.examp_seed import SEED_CARDS

        if not SEED_CARDS:
            return 0

        notetype = _basic_notetype(col)
        if notetype is None:
            return 0
        field_names = [f["name"] for f in notetype["flds"]]
        front_field = "Front" if "Front" in field_names else field_names[0]
        back_field = "Back" if "Back" in field_names else field_names[1]

        deck_id = col.decks.id(DECK_NAME)

        added = 0
        for card in SEED_CARDS:
            note = col.new_note(notetype)
            note[front_field] = card.get("front", "")
            note[back_field] = card.get("back", "")
            tags = card.get("tags") or []
            if tags:
                note.tags = list(tags)
            col.add_note(note, deck_id)
            added += 1

        col.set_config(CONFIG_KEY, True)
        return added
    except Exception:
        # Seeding is best-effort and must never crash the app / startup.
        return 0


def _clean_seed_by_qnum() -> dict[int, tuple[str, str]]:
    """Map SOA question number -> (clean_front_html, clean_back_html)."""
    from anki.brainlift.examp_seed import SEED_CARDS

    out: dict[int, tuple[str, str]] = {}
    for c in SEED_CARDS:
        m = _QNUM_RE.search(c.get("back", ""))
        if m:
            out[int(m.group(1))] = (c.get("front", ""), c.get("back", ""))
    return out


def repair_garbled_seed(col: Collection) -> tuple[int, int]:
    """One-time repair of stale/garbled SOA Exam P seed cards. Returns (repaired, removed).

    Older builds seeded/imported from a *pypdf* extraction that scrambled
    MathType glyph runs, so e.g. ``P[A ∪ B] = 0.7`` was stored as
    ``[ ] 0.7PA B∪=`` — unreadable during review. The bundled
    :mod:`anki.brainlift.examp_seed` is now the clean, layout-aware
    (pdfplumber) content. This heals an already-populated collection in place:

    * For every SOA-attributed note, it rewrites the fields to the clean version
      matched by the note's SOA question number (preserves the note/card id, so
      scheduling + review history are kept and the change syncs cleanly).
    * Notes whose question number has no clean counterpart (the ones the
      readability gate dropped as inherently un-linearizable 2-D math) are
      removed, so no garbled card can surface in review.

    Only touches notes carrying the SOA attribution, so a user's own cards are
    never modified or deleted. Idempotent + guarded by a synced config flag, so
    it runs once on desktop and the fix propagates to the phone via normal sync.
    """
    try:
        if col.get_config(REPAIR_FLAG, False):
            return (0, 0)
        clean = _clean_seed_by_qnum()
        if not clean:
            return (0, 0)
        try:
            nids = col.find_notes('"Sample Questions/Solutions, Q"')
        except Exception:
            nids = col.find_notes("SOA Exam P")
        repaired = 0
        remove_ids: list[int] = []
        for nid in nids:
            note = col.get_note(nid)
            if len(note.fields) < 2:
                continue
            m = _QNUM_RE.search(note.fields[0] + "\n" + note.fields[1])
            if not m:
                continue
            target = clean.get(int(m.group(1)))
            if target is None:
                # SOA card whose question was dropped as un-linearizable garble.
                remove_ids.append(nid)
                continue
            cf, cb = target
            if note.fields[0] != cf or note.fields[1] != cb:
                note.fields[0] = cf
                note.fields[1] = cb
                col.update_note(note)
                repaired += 1
        removed = 0
        if remove_ids:
            col.remove_notes(remove_ids)
            removed = len(remove_ids)
        col.set_config(REPAIR_FLAG, True)
        return (repaired, removed)
    except Exception:
        # Repair is best-effort and must never crash the app / startup.
        return (0, 0)
